### ISSUE TITLE
Login Failed

### ISSUE THREAD

**Issue by GoodlPlus** [iamcco/coc-leetcode#10]
当我登录的时候，发现有报错，TypeError: (t.adapter || o.adapter) is not a function.
neovim 0.5.0-812

<img width="838" alt="捕获" src="https://user-images.githubusercontent.com/42902526/99528713-a9e60c00-29d9-11eb-8474-a1d4037999ea.PNG">

**Comment by iamcco** [comment]
axios 的bug，更新了下，不知道有没有修复

**Comment by GoodlPlus** [comment]
> axios 的bug，更新了下，不知道有没有修复

好像还是不行，
<img width="929" alt="捕获" src="https://user-images.githubusercontent.com/42902526/99624375-2b38af80-2a69-11eb-924a-0a725ef6942a.PNG">

**Comment by iamcco** [comment]
我这里没发复现，有可能和node14有关，我还用的node10
