### ISSUE TITLE
login 失败

### ISSUE THREAD

**Issue by pacmanzou** [iamcco/coc-leetcode#8]
![20201110-193912-0004.png](https://gitee.com/pacmanzou/pictures/raw/master/background/20201110-193912-0004.png)

你好，
可以leetcode.run 但是无法提交和登录 
已经卸载了重装 还是有错，是不是coc.nvim某次更新的关系啊

**Comment by pacmanzou** [comment]
都是最新的版本

**Comment by iamcco** [comment]
没发复现 `:CocInfo` 看卡报啥错了

**Comment by pacmanzou** [comment]
![20201110-194736-0657.png](https://gitee.com/pacmanzou/pictures/raw/master/background/20201110-194736-0657.png)

抱歉 刚才忘记这个图了

**Comment by pacmanzou** [comment]
![20201110-195844-0482.png](https://gitee.com/pacmanzou/pictures/raw/master/background/20201110-195844-0482.png)

**Comment by pacmanzou** [comment]
![2020-11-10_19-44.png](https://gitee.com/pacmanzou/pictures/raw/master/nvim/2020-11-10_19-44.png)

**Comment by iamcco** [comment]
没发复现，用的是最新版本的coc么

**Comment by pacmanzou** [comment]
恩 PlugUpdate之后的 我刚刚把coc PlugClean了，然后再次安装，解决了这个问题
不过之前的plugUpdate为什么不好使，它不是也是更新的吗？
不过总算可以愉快的刷题了....

**Comment by pacmanzou** [comment]
恩 PlugUpdate之后的 我刚刚把coc PlugClean了，然后再次安装，解决了这个问题
不过之前的plugUpdate为什么不好使，它不是也是更新的吗？
不过总算可以愉快的刷题了....

**Comment by pacmanzou** [comment]
非常喜欢你做的插件 哈哈
